# Ascultă pe portul standard MQTT pe toate interfețele de rețea interne
listener 1883 0.0.0.0

# Ascultă pe portul pentru WebSockets (util pentru debugging viitor)
listener 9001 0.0.0.0
protocol websockets

# Permitem conexiuni fără parolă strict în interiorul rețelei Docker
# (Într-un mediu de producție real, aici am configura autentificare TLS/SSL)
allow_anonymous true

# Persistența mesajelor în caz de restart al containerului
persistence true
persistence_location /mosquitto/data/