[network]
net_id="000000"
enabled_regions=["eu868"]

[api]
bind="0.0.0.0:8080"
secret="un-secret-foarte-sigur-pentru-licenta-ta-2025"

[postgresql]
dsn="postgres://admin:secretpassword@postgres/chirpstack?sslmode=disable"

[redis]
servers=["redis://redis:6379"]

[integration]
enabled=["mqtt"]

[integration.mqtt]
server="tcp://mosquitto:1883"
json=true
